# Generated by Django 2.0.5 on 2018-05-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subletPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_Stay', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('housing_Type1', models.CharField(max_length=100)),
                ('housing_Type2', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField(default=0)),
                ('num_Bathrooms', models.IntegerField(default=0)),
                ('num_Beds', models.IntegerField(default=0)),
                ('num_Bedrooms', models.IntegerField(default=0)),
                ('num_Capable_of_Housing', models.IntegerField(default=0)),
                ('furnished', models.BooleanField(default=False)),
                ('private_Bathroom', models.BooleanField(default=False)),
                ('essentials', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('heat', models.BooleanField(default=False)),
                ('air_Conditioning', models.BooleanField(default=False)),
                ('desk', models.BooleanField(default=False)),
                ('fireplace', models.BooleanField(default=False)),
                ('iron', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('private_Entrance', models.BooleanField(default=False)),
                ('smoke_Detector', models.BooleanField(default=False)),
                ('carbon_Monoxide_Detector', models.BooleanField(default=False)),
                ('first_Aid_Kit', models.BooleanField(default=False)),
                ('safety_Card', models.BooleanField(default=False)),
                ('fire_Extinguisher', models.BooleanField(default=False)),
                ('bedroom_Lock', models.BooleanField(default=False)),
                ('living_Room', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('laundry_Washer', models.BooleanField(default=False)),
                ('laundry_Dryer', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('image1', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image2', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image3', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image4', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image5', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image6', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image7', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image8', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image9', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image10', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image11', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
                ('image12', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media')),
            ],
        ),
    ]
