# Generated by Django 2.0.5 on 2018-05-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subletPost',
            new_name='sublet',
        ),
    ]
