# Generated by Django 2.0.5 on 2018-05-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0002_auto_20180526_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublet',
            name='hot_tub',
            field=models.BooleanField(default=False),
        ),
    ]
